#SITE CONFIGURATIONS
baseurl: "" # the subpath of your site, e.g. /blo
url: "https://jcruiz.co"

#THEME SPECIFIC CONFIGURATION - Hydeout
remote_theme: fongandrew/hydeout

# A. Site Settings /SEO options
title: The Other Radio
tagline: 
description: Juan Camilo Ruiz views on product management, traveling and web stuff

# SEO
analytics: true
author:
  name: Juan Camilo Ruiz
  url: https://twitter.com/juanca
google_analytics: UA-44281567-1

# B. Navigation
paginate: 5
sidebar_home_link: true

github:
  repo: https://github.com/jcruiz/blog
twitter: juanca

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist


# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor

include:
  - .well-known/
  - pages
  - categories

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false